### ISSUE TITLE
vision encoder

### ISSUE THREAD

**Issue by Kimsure** [WePOINTS/WePOINTS#37]
Impressive work! You mentioned that you used NaViT to replace CLIP I.E. Do you have any NaViT model or weights that is pretrained following CLIP's contrastive learning setting

**Comment by YuanLiuuuuuu** [comment]
Thank you for your interest in POINTS1.5. We use the pre-trained NaViT from Qwen2-VL-7B, rather than pre-training it ourselves. If you want to use the NaViT weights in POINTS1.5, you can load the POINTS1.5 model and save the [vision_encoder](https://huggingface.co/WePOINTS/POINTS-1-5-Qwen-2-5-7B-Chat/blob/main/modeling_pointsv15_chat.py#L39) yourself. We have also created a [NaViT module file](https://github.com/WePOINTS/WePOINTS/blob/main/wepoints/models/vision/qwen2_vl_navit.py), which you can use to load the weights you saved.

**Comment by Kimsure** [comment]
Thanks, I will try it
